baseURL = 'https://writings.kushaljuneja.in'
languageCode = 'en-us'
title = 'Writings'

[Menus]
main = [
    {Name = "About Me", URL = "https://www.kushaljuneja.in"},
]


[params]
subtitle = "by Kushal Juneja"
description = "Here, I write about topics that feel like spinning plates to me: whatever inspires curiosity and investigation."

[taxonomies]
category = "categories"
tag = "tags"


[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1